export const SET_CURRENCY_NAMES = 'SET_CURRENCY_NAMES';
export const SET_CURRENCY_RATES = 'SET_CURRENCY_RATES';
export const SET_LOADED = 'SET_LOADED';
export const CHANGE_BASE_CURRENCY = 'CHANGE_BASE_CURRENCY';
export const CHANGE_BASE_CURRENCY_VALUE = 'CHANGE_BASE_CURRENCY_VALUE';
export const ADD_CURRENCY = 'ADD_CURRENCY';
export const DELETE_CURRENCY = 'DELETE_CURRENCY';
